### ISSUE TITLE
Problem with loading tiff images

### ISSUE THREAD

**Issue by oeway** [photopea/UTIF.js#29]
I have some images produced from a software called [ImageJ](https://imagej.nih.gov/ij/download.html), when I try to load it in photopea, the loading get stucked.
This is the error:
<img width="582" alt="screen shot 2018-04-21 at 5 22 40 pm" src="https://user-images.githubusercontent.com/478667/39085834-e7dc1fd2-4588-11e8-91c7-5d9c06e931c8.png">

Here is my file: https://www.dropbox.com/s/7vtuifu67bswlp7/microtubules-raw-500frames.tif?dl=0
(16-bits grayscale, 500 frames, 128x128 pixels)
<img width="327" alt="screen shot 2018-04-21 at 5 24 32 pm" src="https://user-images.githubusercontent.com/478667/39085845-1e08909a-4589-11e8-904c-6bc093bb3c62.png">

**Comment by photopea** [comment]
Hi, I can not download your file (it says 404). Can you send it e.g. to support@photopea.com ?

**Comment by oeway** [comment]
hi, sorry, I removed it accidentally. This one should work: https://www.dropbox.com/s/7vtuifu67bswlp7/microtubules-raw-500frames.tif?dl=0

**Comment by photopea** [comment]
Apparently, the compression tag is missing in your file (which I have never seen before). In that case, it should be treated as no compression. I fixed it (please, update your UTIF.js).

**Comment by oeway** [comment]
Thanks for the quick fix, it works now.

**Comment by oeway** [comment]
Hi again, I just notice that the version I installed from npm still have this problem. I checked the code in npm with version number  `utif@1.3.0`, it's different from the master branch. Could you please update the npm? Thank you.

**Comment by photopea** [comment]
Hi, I do not use npm. Could @Scimonster update it?  I thought it would be possible to set npm to update automatically each time the GitHub repository changes, but it is not possible :(
